-- =============================================================================
-- seed.sql — test data for local development (`supabase db reset` runs this).
--
-- Creates: 1 admin, 2 brands (1 active campaign each), 3 creators,
-- approved matches (affiliate links auto-generated by trigger), a few
-- conversions, and some click events.
--
-- All users share the password: password123
-- =============================================================================

-- pgcrypto provides crypt()/gen_salt() for the password hashes below.
create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Fixed UUIDs so we can wire relationships deterministically.
-- ---------------------------------------------------------------------------
-- auth.users / profiles
--   admin    : 00000000-0000-0000-0000-000000000001
--   brand 1  : 00000000-0000-0000-0000-000000000011
--   brand 2  : 00000000-0000-0000-0000-000000000012
--   creator 1: 00000000-0000-0000-0000-000000000021
--   creator 2: 00000000-0000-0000-0000-000000000022
--   creator 3: 00000000-0000-0000-0000-000000000023

-- ---------------------------------------------------------------------------
-- auth.users — the on_auth_user_created trigger creates the matching profiles
-- from raw_user_meta_data (role + full_name).
-- ---------------------------------------------------------------------------
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
  created_at, updated_at
)
values
  ('00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000001',
   'authenticated', 'authenticated', 'admin@example.com', crypt('password123', gen_salt('bf')),
   now(), '{"provider":"email","providers":["email"]}',
   '{"role":"admin","full_name":"Platform Admin"}', now(), now()),

  ('00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000011',
   'authenticated', 'authenticated', 'brand1@example.com', crypt('password123', gen_salt('bf')),
   now(), '{"provider":"email","providers":["email"]}',
   '{"role":"brand","full_name":"Glow Cosmetics"}', now(), now()),

  ('00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000012',
   'authenticated', 'authenticated', 'brand2@example.com', crypt('password123', gen_salt('bf')),
   now(), '{"provider":"email","providers":["email"]}',
   '{"role":"brand","full_name":"TechZone TN"}', now(), now()),

  ('00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000021',
   'authenticated', 'authenticated', 'creator1@example.com', crypt('password123', gen_salt('bf')),
   now(), '{"provider":"email","providers":["email"]}',
   '{"role":"creator","full_name":"Adam Cheikhrouhou"}', now(), now()),

  ('00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000022',
   'authenticated', 'authenticated', 'creator2@example.com', crypt('password123', gen_salt('bf')),
   now(), '{"provider":"email","providers":["email"]}',
   '{"role":"creator","full_name":"Sarra Ben Ali"}', now(), now()),

  ('00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000023',
   'authenticated', 'authenticated', 'creator3@example.com', crypt('password123', gen_salt('bf')),
   now(), '{"provider":"email","providers":["email"]}',
   '{"role":"creator","full_name":"Yassine Tech"}', now(), now())
on conflict (id) do nothing;

-- GoTrue scans these token columns as Go strings on login; NULL -> 500
-- "Database error querying schema". Manual SQL inserts leave them NULL, so
-- normalise them to '' (the value GoTrue itself uses for new signups).
update auth.users set
  confirmation_token         = coalesce(confirmation_token, ''),
  recovery_token             = coalesce(recovery_token, ''),
  email_change               = coalesce(email_change, ''),
  email_change_token_new     = coalesce(email_change_token_new, ''),
  email_change_token_current = coalesce(email_change_token_current, ''),
  phone_change               = coalesce(phone_change, ''),
  phone_change_token         = coalesce(phone_change_token, ''),
  reauthentication_token     = coalesce(reauthentication_token, '')
where id in (
  '00000000-0000-0000-0000-000000000001',
  '00000000-0000-0000-0000-000000000011',
  '00000000-0000-0000-0000-000000000012',
  '00000000-0000-0000-0000-000000000021',
  '00000000-0000-0000-0000-000000000022',
  '00000000-0000-0000-0000-000000000023'
);

-- Email identities so the seeded users can actually sign in.
insert into auth.identities (
  provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at
)
select
  u.id, u.id,
  jsonb_build_object('sub', u.id::text, 'email', u.email),
  'email', now(), now(), now()
from auth.users u
where u.id in (
  '00000000-0000-0000-0000-000000000001',
  '00000000-0000-0000-0000-000000000011',
  '00000000-0000-0000-0000-000000000012',
  '00000000-0000-0000-0000-000000000021',
  '00000000-0000-0000-0000-000000000022',
  '00000000-0000-0000-0000-000000000023'
)
on conflict do nothing;

-- Safety net: ensure profiles exist with correct role/name even if the
-- trigger was not active when users were inserted.
insert into profiles (id, role, full_name, email)
values
  ('00000000-0000-0000-0000-000000000001', 'admin',   'Platform Admin',     'admin@example.com'),
  ('00000000-0000-0000-0000-000000000011', 'brand',   'Glow Cosmetics',     'brand1@example.com'),
  ('00000000-0000-0000-0000-000000000012', 'brand',   'TechZone TN',        'brand2@example.com'),
  ('00000000-0000-0000-0000-000000000021', 'creator', 'Adam Cheikhrouhou',  'creator1@example.com'),
  ('00000000-0000-0000-0000-000000000022', 'creator', 'Sarra Ben Ali',      'creator2@example.com'),
  ('00000000-0000-0000-0000-000000000023', 'creator', 'Yassine Tech',       'creator3@example.com')
on conflict (id) do update
  set role = excluded.role, full_name = excluded.full_name, email = excluded.email;

-- ---------------------------------------------------------------------------
-- Brands
-- ---------------------------------------------------------------------------
insert into brands (id, profile_id, store_name, store_url, gtm_id, description, konnect_deposit, is_verified)
values
  ('b0000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000011',
   'Glow Cosmetics', 'https://glow.converty.shop', 'GTM-GLOW01', 'Beauty & skincare brand', 500, true),
  ('b0000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000012',
   'TechZone TN', 'https://techzone.converty.shop', 'GTM-TECH02', 'Gadgets & accessories', 1000, true)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Creators
-- ---------------------------------------------------------------------------
insert into creators (id, profile_id, niche, bio, instagram_url, audience_size, iban, is_verified)
values
  ('c0000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000021',
   'beauty', 'Beauty content creator', 'https://instagram.com/adam', 45000, 'TN5904018104003691234567', true),
  ('c0000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000022',
   'fashion', 'Fashion & lifestyle', 'https://instagram.com/sarra', 120000, 'TN5904018104003697654321', true),
  ('c0000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000023',
   'tech', 'Tech reviews', 'https://instagram.com/yassine', 30000, 'TN5904018104003691112223', false)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Campaigns (one active per brand)
-- ---------------------------------------------------------------------------
insert into campaigns (id, brand_id, product_name, product_url, commission_rate, platform_fee_rate, budget, status, starts_at)
values
  ('ca000000-0000-0000-0000-000000000001', 'b0000000-0000-0000-0000-000000000001',
   'Vitamin C Serum', 'https://glow.converty.shop/p/vitamin-c-serum', 20, 20, 2000, 'active', now()),
  ('ca000000-0000-0000-0000-000000000002', 'b0000000-0000-0000-0000-000000000002',
   'Wireless Earbuds Pro', 'https://techzone.converty.shop/p/earbuds-pro', 15, 25, 3000, 'active', now())
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Matches — inserting with status 'approved' fires the trigger that
-- auto-generates an affiliate_link for each.
-- ---------------------------------------------------------------------------
insert into matches (id, campaign_id, creator_id, status)
values
  ('aa000000-0000-0000-0000-000000000001', 'ca000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000001', 'approved'),
  ('aa000000-0000-0000-0000-000000000002', 'ca000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000002', 'approved'),
  ('aa000000-0000-0000-0000-000000000003', 'ca000000-0000-0000-0000-000000000002', 'c0000000-0000-0000-0000-000000000003', 'approved')
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Conversions — ref the auto-generated affiliate links by lookup.
-- The before-insert trigger fills commission_amount / platform_fee and bumps
-- campaign.spent, so we only provide sale_amount + status.
-- ---------------------------------------------------------------------------
insert into conversions (affiliate_link_id, campaign_id, creator_id, brand_id, order_reference, sale_amount, source, status)
select al.id, al.campaign_id, al.creator_id, c.brand_id, v.order_reference, v.sale_amount, 'sheet', v.status::conversion_status
from (values
  ('aa000000-0000-0000-0000-000000000001', 'ORD-1001', 120.0, 'confirmed'),
  ('aa000000-0000-0000-0000-000000000001', 'ORD-1002',  80.0, 'confirmed'),
  ('aa000000-0000-0000-0000-000000000002', 'ORD-1003', 150.0, 'pending'),
  ('aa000000-0000-0000-0000-000000000003', 'ORD-2001', 220.0, 'confirmed')
) as v(match_id, order_reference, sale_amount, status)
join affiliate_links al on al.match_id = v.match_id::uuid
join campaigns c on c.id = al.campaign_id
on conflict (order_reference) where order_reference is not null do nothing;

-- ---------------------------------------------------------------------------
-- Click events — a handful per affiliate link.
-- ---------------------------------------------------------------------------
insert into click_events (affiliate_link_id, ip_address, user_agent, device, country)
select al.id, '197.0.0.1'::inet,
       'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X)', 'mobile', 'TN'
from affiliate_links al, generate_series(1, 5);
