import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { Wallet } from "lucide-react";
import { createSupabaseServer } from "@/lib/supabase/server";
import { getAdminPayouts } from "@/lib/admin";

export const metadata: Metadata = { title: "Payouts | Admin" };

function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
}

function formatDate(value: string | null): string {
  if (!value) return "—";
  return new Date(value).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

const STATUS_STYLES: Record<string, string> = {
  completed: "bg-[var(--accent-lime-bg)] text-[var(--accent-lime-bright)]",
  processing: "bg-[var(--accent-violet)]/20 text-[var(--accent-violet-light)]",
  pending: "bg-amber-500/15 text-amber-400",
  failed: "bg-red-500/15 text-red-400",
};

export default async function AdminPayoutsPage() {
  const supabase = await createSupabaseServer();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const payouts = await getAdminPayouts();
  const totalDisbursed = payouts
    .filter((p) => p.status === "completed")
    .reduce((s, p) => s + p.amount, 0);

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h2
            className="text-[32px] font-bold text-[var(--text-primary)]"
            style={{ fontFamily: "var(--font-space-grotesk)" }}
          >
            Payouts ({payouts.length})
          </h2>
          <p className="mt-1 text-[var(--text-secondary)]">
            Creator payouts. Generated by the payout edge functions.
          </p>
        </div>
        <div className="rounded-xl border border-[var(--border-outline)] bg-[var(--bg-card)] px-5 py-3">
          <p className="text-xs text-[var(--text-secondary)]">Total disbursed</p>
          <p
            className="text-xl font-bold text-[var(--accent-lime-bright)]"
            style={{ fontFamily: "var(--font-space-grotesk)" }}
          >
            {formatCurrency(totalDisbursed)}
          </p>
        </div>
      </div>

      {payouts.length === 0 ? (
        <div className="flex flex-col items-center justify-center gap-3 rounded-2xl border border-[var(--border-outline)] bg-[var(--bg-card)] py-20 text-center">
          <Wallet className="h-10 w-10 text-[var(--text-secondary)]" />
          <p className="text-[var(--text-secondary)]">No payouts yet.</p>
        </div>
      ) : (
        <div className="overflow-hidden rounded-2xl border border-[var(--border-outline)] bg-[var(--bg-card)]">
          <div className="overflow-x-auto">
            <table className="w-full min-w-[820px]">
              <thead>
                <tr className="border-b border-[var(--border-outline)] text-left text-xs font-semibold tracking-wider text-[var(--text-secondary)] uppercase">
                  <th className="px-6 py-4">Creator</th>
                  <th className="px-6 py-4">Amount</th>
                  <th className="px-6 py-4">Method</th>
                  <th className="px-6 py-4">Period</th>
                  <th className="px-6 py-4">Reference</th>
                  <th className="px-6 py-4">Status</th>
                </tr>
              </thead>
              <tbody>
                {payouts.map((p) => (
                  <tr key={p.id} className="border-b border-[var(--border-faint)] last:border-0">
                    <td className="px-6 py-4 font-medium text-[var(--text-primary)]">
                      {p.creatorName}
                    </td>
                    <td className="px-6 py-4 text-sm font-semibold text-[var(--text-primary)]">
                      {formatCurrency(p.amount)}
                    </td>
                    <td className="px-6 py-4 text-sm capitalize text-[var(--text-on-surface)]">
                      {p.method}
                    </td>
                    <td className="px-6 py-4 text-sm text-[var(--text-secondary)]">
                      {formatDate(p.periodStart)} – {formatDate(p.periodEnd)}
                    </td>
                    <td className="px-6 py-4 text-sm text-[var(--text-secondary)]">
                      {p.reference ?? "—"}
                    </td>
                    <td className="px-6 py-4">
                      <span
                        className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold capitalize ${
                          STATUS_STYLES[p.status] ?? "bg-[var(--bg-hover)] text-[var(--text-secondary)]"
                        }`}
                      >
                        {p.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
